sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8
  - 7
  - 6
  - node
before_script:
  - npm prune
script:
  - npm run build
  - npm test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  # - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
